name: Echo
options:
  bundleIdPrefix: com.jeffhobbs
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
settings:
  base:
    DEVELOPMENT_TEAM: YKF353373Y
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
targets:
  Echo:
    type: application
    platform: macOS
    sources:
      - App
      - Sources
    info:
      path: App/Info.plist
      properties:
        CFBundleDisplayName: Echo
        CFBundleIconFile: AppIcon
        LSApplicationCategoryType: public.app-category.music
        NSHumanReadableCopyright: "Jeff Hobbs"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jeffhobbs.echo
